#!/usr/bin/env bash
# Create a new autogenerated migration.
# Usage: ./entrypoints/makemigration.sh "describe your change"
set -euo pipefail
cd "$(dirname "$0")/.."

MESSAGE="${1:-migration}"
echo "[otis] Creating migration: ${MESSAGE}"
alembic revision --autogenerate -m "${MESSAGE}"
echo "[otis] Migration created under migrations/versions/."
